#include "robot/mcl_rerun.hpp"
#include "robot/oekf_rerun.hpp"
#include "robot/start_pose.hpp"
#include "robot/chassis_config.hpp"
#include "robot/hardware.hpp"
#include "robot/motors.hpp"
#include "robot/embedded_route.hpp"

#include "lemlib/api.hpp"
#include "pros/rtos.hpp"

#include <algorithm>
#include <cmath>
#include <cstdlib>
#include <fstream>
#include <sstream>
#include <string>

// 1 = replay the route compiled into the firmware
//     (include/robot/embedded_route.hpp, generated by tools/embed_route.sh
//     from path/dtData.txt). No SD card needed.
// 0 = read /usd/dtData.txt from the SD card.
#define USE_EMBEDDED_ROUTE 1

namespace mcl {

namespace {

constexpr double PI       = 3.14159265358979323846;
constexpr double MM_PER_IN = 25.4;
constexpr const char* DATA_PATH = "/usd/dtData.txt";

// Sensor mount geometry now lives in robot/field_model.hpp (field::FRONT,
// BACK, LEFT, RIGHT) so it is measured/tuned in ONE place.

// Distance reading validity window. VEX V5 Distance: 20-2000 mm range,
// get()==9999 means no object, confidence only valid above 200 mm.
constexpr double DIST_MIN_MM  = 20.0;
constexpr double DIST_MAX_MM  = 2000.0;
constexpr double CONF_DIST_MM = 200.0; // confidence meaningful only above this
constexpr int    CONF_GATE    = 40;    // VEX 0..63

// Obstacle reject: if a beam reads more than this far from the mapped wall
// distance (at the current best estimate), it hit something not in the map
// (long goal, game piece, another robot) — drop it instead of trusting it.
constexpr double OBSTACLE_REJECT_IN = 12.0;

// Wall-normal gate: skip sensor when its pointing dir is more than this
// many radians off from the perpendicular to the wall it would hit.
constexpr double WALL_NORMAL_GATE_RAD = 30.0 * PI / 180.0;

// Roughening: jitter added to each particle after resampling so the cloud
// keeps diversity instead of collapsing to a single point (var -> 0).
// Keeps the filter able to recover and the variance meaningful.
constexpr double ROUGHEN_XY_IN  = 0.75;             // inches
constexpr double ROUGHEN_TH_RAD = 1.5 * PI / 180.0; // radians

// Thrun sample_motion_model_odometry alphas. Mock values; tune later.
constexpr double DEFAULT_ALPHAS[4] = {0.05, 0.02, 0.02, 0.05};

// Sensor noise (inches^2). Tune from bench measurements.
constexpr double R_SENSOR = 3.0;

// Resample trigger.
constexpr double NEFF_RESAMPLE_THRESH = (double)N / 2.0;

// Partial correction shape. trust = clamp(1 - var_xy/VAR_FULL_TRUST, 0, 1).
// When var_xy >= VAR_FULL_TRUST, no correction (trust LemLib alone).
// When var_xy ≈ 0, full correction.
constexpr double VAR_FULL_TRUST = 4.0;  // inches^2

// Replay tuning — mirrors oekf_rerun for parity.
constexpr int    WAYPOINT_SKIP      = 8;
constexpr int    MIN_SPEED          = 70;
constexpr int    MAX_SPEED          = 110;
constexpr float  EARLY_EXIT_MAX     = 6.0f;
constexpr double TURN_DETECT_DEG    = 25.0;
constexpr double TURN_RATIO_THRESH  = 8.0;
constexpr double SHORT_MOVE_IN      = 4.0;
constexpr double TURN_THRESHOLD_DEG = 15.0;
constexpr int    TURN_TIMEOUT_MS    = 500;
constexpr double TIMEOUT_MULTIPLIER = 1.6;
constexpr double MAX_SPEED_IPS      = 48.0;


// ─── RNG ────────────────────────────────────────────────────────
// std::rand is fine for a 200-500-particle mock. Seed once in init().

double sampleU01() {
    return ((double)std::rand() + 1.0) / ((double)RAND_MAX + 2.0);
}

// Box-Muller standard normal.
double sampleN01() {
    double u1 = sampleU01();
    double u2 = sampleU01();
    return std::sqrt(-2.0 * std::log(u1)) * std::cos(2.0 * PI * u2);
}

// Sample N(0, sigma^2). Sign of sigma doesn't matter; we square it.
double sampleN(double sigma) { return sampleN01() * std::abs(sigma); }

// Clamp a coordinate to the field so particles can't drift off into
// nonsense (where raycasts are meaningless and recovery is impossible).
double clampF(double v) {
    if (v < 0.0) return 0.0;
    if (v > oekf::FIELD_IN) return oekf::FIELD_IN;
    return v;
}


// Sensor-model geometry helpers (raycast, grazing-angle, sensor world
// pose) now live in robot/field_model.hpp as field:: functions.


// ─── Replay helpers ────────────────────────────────────────────

struct Frame {
    double x, y, t;
    int r1, r2, y_btn, b_btn, l2, l1, right_btn, x_btn;
};

bool parse_frame(const std::string& line, Frame& out) {
    std::stringstream ss(line);
    std::string tok;
    try {
        std::getline(ss, tok, ' '); out.x         = std::stod(tok);
        std::getline(ss, tok, ' '); out.y         = std::stod(tok);
        std::getline(ss, tok, ' '); out.t         = std::stod(tok);
        std::getline(ss, tok, ' '); out.r1        = std::stoi(tok);
        std::getline(ss, tok, ' '); out.r2        = std::stoi(tok);
        std::getline(ss, tok, ' '); out.y_btn     = std::stoi(tok);
        std::getline(ss, tok, ' '); out.b_btn     = std::stoi(tok);
        std::getline(ss, tok, ' '); out.l2        = std::stoi(tok);
        std::getline(ss, tok, ' '); out.l1        = std::stoi(tok);
        std::getline(ss, tok, ' '); out.right_btn = std::stoi(tok);
        std::getline(ss, tok, ' '); out.x_btn     = std::stoi(tok);
    } catch (...) { return false; }
    return true;
}

void replay_mech(const Frame& f,
                 bool& prev_l1, bool& prev_right, bool& prev_x,
                 bool& wingState, bool& matchloadState, bool& limiterState) {
    if (f.r1) {
        outtake(200); intake(200); middletake(600);
        limiter.set_value(1);
    } else if (f.r2) {
        intake(200); middletake(600); outtake(200);
        limiter.set_value(0);
    } else if (f.y_btn) {
        limiter.set_value(0);
        outtake(-200); intake(200); middletake(600);
    } else if (f.b_btn) {
        limiter.set_value(0);
        outtake(-55); intake(200); middletake(600);
    } else if (f.l2) {
        outtake(-200); intake(-200); middletake(-600);
    } else {
        intake(0); outtake(0); middletake(0);
    }
    if (f.l1 && !prev_l1) {
        wingState = !wingState;
        wing.set_value(wingState);
    }
    prev_l1 = f.l1;
    if (f.right_btn && !prev_right) {
        matchloadState = !matchloadState;
        matchLoad.set_value(matchloadState);
    }
    prev_right = f.right_btn;
    if (f.x_btn && !prev_x) {
        limiterState = !limiterState;
        limiter.set_value(limiterState);
        // limiter_light disabled — port 6 collision
    }
    prev_x = f.x_btn;
}

} // anonymous namespace


// ─── init ───────────────────────────────────────────────────────
void init(Filter& f,
          double x0, double y0, double theta0_rad,
          double sigma_xy_in, double sigma_theta_rad) {
    std::srand(pros::millis());

    for (int i = 0; i < N; ++i) {
        f.particles[i].x     = x0          + sampleN(sigma_xy_in);
        f.particles[i].y     = y0          + sampleN(sigma_xy_in);
        f.particles[i].theta = theta0_rad  + sampleN(sigma_theta_rad);
        f.particles[i].w     = 1.0 / N;
    }
    f.x_mean     = x0;
    f.y_mean     = y0;
    f.theta_mean = theta0_rad;
    f.var_xy     = 2.0 * sigma_xy_in * sigma_xy_in;
    f.n_eff      = (double)N;
}


// ─── set_heading (pin orientation to a trusted gyro) ───────────
//
// On a known rectangular field the VEX IMU tracks heading far better than
// the distance sensors can ever recover it (the walls barely constrain
// orientation). Standard practice for MCL with a good gyro is to NOT let
// the particle headings free-run: pin every particle to the measured
// heading each tick, with a small jitter for slack. This collapses the
// filter to 2-D (x, y) estimation and removes the wrong-wall-association
// failure mode that makes the estimate explode.
void set_heading(Filter& f, double theta_rad, double sigma_rad) {
    for (int i = 0; i < N; ++i)
        f.particles[i].theta = theta_rad + sampleN(sigma_rad);
}


// ─── predict (body-frame motion model) ─────────────────────────
//
// Thrun-style sample_motion_model_odometry, but parameterized on the
// odom-pod outputs we have:
//   d_forward: along robot's heading (vertical pod delta, in)
//   d_lateral: perpendicular to heading (horizontal pod delta, in)
//   dtheta_rad: heading delta (rad)
//
// Per particle: project (d_forward, d_lateral) into its own heading,
// then add noise scaled by motion magnitude.
void predict(Filter& f,
             double d_forward, double d_lateral, double dtheta_rad,
             const double alphas[4]) {
    const double a1 = alphas[0];
    const double a2 = alphas[1];
    const double a3 = alphas[2];
    const double a4 = alphas[3];

    const double abs_dtheta = std::abs(dtheta_rad);
    const double trans_mag  = std::sqrt(d_forward * d_forward + d_lateral * d_lateral);

    // Rotation noise variance grows with |dtheta| and |trans|.
    const double sigma_rot   = std::sqrt(a1 * abs_dtheta + a2 * trans_mag);
    // Translation noise variance grows with |trans| and |dtheta|.
    const double sigma_trans = std::sqrt(a3 * trans_mag + a4 * abs_dtheta);

    for (int i = 0; i < N; ++i) {
        // Sample noisy version of this particle's motion.
        const double df_noisy = d_forward + sampleN(sigma_trans);
        const double dl_noisy = d_lateral + sampleN(sigma_trans);
        const double dt_noisy = dtheta_rad + sampleN(sigma_rot);

        // Rotate body delta into world frame using THIS particle's heading.
        // theta=0 means facing +Y, CW positive ⇒ heading vec = (sin θ, cos θ).
        // Lateral (+X in body) is heading rotated +90° CW = (cos θ, -sin θ).
        const double th  = f.particles[i].theta;
        const double sin_th = std::sin(th);
        const double cos_th = std::cos(th);

        const double dx_world = df_noisy * sin_th + dl_noisy * cos_th;
        const double dy_world = df_noisy * cos_th - dl_noisy * sin_th;

        f.particles[i].x     = clampF(f.particles[i].x + dx_world);
        f.particles[i].y     = clampF(f.particles[i].y + dy_world);
        f.particles[i].theta += dt_noisy;
    }
}


// ─── update (one wall reading) ─────────────────────────────────
bool update(Filter& f,
            const field::SensorMount& mount,
            int raw_mm,
            int confidence,
            double R_noise) {
    // Validity gate, honoring the sensor spec: reject out-of-range / 9999,
    // accept close readings unconditionally (confidence is unavailable but
    // distance is good to +/-15 mm), gate far readings on confidence.
    if (raw_mm < DIST_MIN_MM || raw_mm > DIST_MAX_MM)        return false;
    if (raw_mm > CONF_DIST_MM && confidence < CONF_GATE)     return false;

    // raw is the distance from the sensor FACE to whatever it hit. We now
    // raycast from the sensor's true world position, so NO center offset is
    // added — the geometry is handled by the mount (field_model.hpp).
    const double measured = raw_mm / MM_PER_IN;
    const double inv_2R   = 1.0 / (2.0 * R_noise);

    // Obstacle reject: compare against the wall distance expected at the
    // current best estimate. If the beam disagrees a lot, it hit something
    // not in the map (long goal, game piece, another robot) or the wall at
    // a useless angle — drop the whole reading rather than corrupt the cloud.
    {
        double sx, sy, sang;
        field::sensor_world(f.x_mean, f.y_mean, f.theta_mean, mount, sx, sy, sang);
        const double exp_mean = field::raycast(sx, sy, sang);
        if (std::abs(measured - exp_mean) > OBSTACLE_REJECT_IN) return false;
    }

    // Log-sum-exp trick to keep weights stable for large innovations.
    // We accumulate log-weights, then normalize by subtracting max
    // before exp. Static to avoid 4KB stack allocation per tick.
    static double log_w[N];
    double max_logw = -1e300;

    for (int i = 0; i < N; ++i) {
        double sx, sy, sang;
        field::sensor_world(f.particles[i].x, f.particles[i].y,
                            f.particles[i].theta, mount, sx, sy, sang);

        int wall = -1;
        const double expected = field::raycast(sx, sy, sang, &wall);

        // Wall-normal gate: if the sensor would hit the wall at a grazing
        // angle, the reading is unreliable for this particle. Skip the
        // likelihood update (treat as uninformative).
        double ll;
        if (field::grazing_angle(sang, wall) > WALL_NORMAL_GATE_RAD) {
            ll = 0.0;  // uninformative
        } else {
            const double innov = measured - expected;
            ll = -innov * innov * inv_2R;
        }

        log_w[i] = std::log(f.particles[i].w + 1e-300) + ll;
        if (log_w[i] > max_logw) max_logw = log_w[i];
    }

    // Normalize.
    double total = 0.0;
    for (int i = 0; i < N; ++i) {
        f.particles[i].w = std::exp(log_w[i] - max_logw);
        total += f.particles[i].w;
    }
    if (total < 1e-12) {
        // Total collapse: no particle matches THIS reading. Almost always a
        // single noisy/out-of-range sensor frame, not a genuinely lost robot.
        // Re-scattering across the whole field here is destructive: if only
        // one axis has a valid wall next tick, the other axis never recovers
        // and the estimate freezes at a wrong value. Instead, keep particle
        // positions and just reset weights uniform — i.e. ignore this bad
        // update and trust the existing belief.
        for (int i = 0; i < N; ++i) f.particles[i].w = 1.0 / N;
    } else {
        for (int i = 0; i < N; ++i) f.particles[i].w /= total;
    }
    return true;
}


// ─── resample (Thrun low-variance) ─────────────────────────────
void resample(Filter& f) {
    // Static to avoid ~16KB stack allocation per call.
    static Particle next[N];
    const double step = 1.0 / N;
    const double r    = step * sampleU01();
    double c = f.particles[0].w;
    int i = 0;
    for (int m = 0; m < N; ++m) {
        const double U = r + m * step;
        while (U > c && i < N - 1) {
            ++i;
            c += f.particles[i].w;
        }
        next[m]   = f.particles[i];
        next[m].w = 1.0 / N;
    }
    // Roughening — re-inject diversity so the cloud doesn't collapse.
    for (int m = 0; m < N; ++m) {
        next[m].x     = clampF(next[m].x + sampleN(ROUGHEN_XY_IN));
        next[m].y     = clampF(next[m].y + sampleN(ROUGHEN_XY_IN));
        next[m].theta += sampleN(ROUGHEN_TH_RAD);
    }
    for (int m = 0; m < N; ++m) f.particles[m] = next[m];
}


// ─── summarize ─────────────────────────────────────────────────
void summarize(Filter& f) {
    double sx = 0, sy = 0, sc = 0, ss = 0, sw2 = 0;
    for (int i = 0; i < N; ++i) {
        sx  += f.particles[i].x * f.particles[i].w;
        sy  += f.particles[i].y * f.particles[i].w;
        sc  += std::cos(f.particles[i].theta) * f.particles[i].w;
        ss  += std::sin(f.particles[i].theta) * f.particles[i].w;
        sw2 += f.particles[i].w * f.particles[i].w;
    }
    f.x_mean     = sx;
    f.y_mean     = sy;
    f.theta_mean = std::atan2(ss, sc);

    // Weighted variance of x,y around the mean (trace of cov, in^2).
    double var = 0.0;
    for (int i = 0; i < N; ++i) {
        const double dx = f.particles[i].x - sx;
        const double dy = f.particles[i].y - sy;
        var += f.particles[i].w * (dx * dx + dy * dy);
    }
    f.var_xy = var;
    f.n_eff  = (sw2 > 1e-12) ? (1.0 / sw2) : (double)N;
}


// ─── rerun (top-level replay) ──────────────────────────────────
void rerun(double start_x_in, double start_y_in, double start_theta_deg) {
#if USE_EMBEDDED_ROUTE
    std::istringstream fs(route::EMBEDDED_DATA);
    controller.print(0, 0, "MCL embedded route");
    pros::delay(200);
#else
    if (!pros::usd::is_installed()) {
        controller.print(0, 0, "FAIL: no SD card  ");
        pros::delay(1000);
        return;
    }
    std::ifstream fs(DATA_PATH);
    if (!fs.is_open()) {
        controller.print(0, 0, "FAIL: no file     ");
        pros::delay(1000);
        return;
    }
#endif

    int lineCount = 0;
    std::string countLine;
    while (std::getline(fs, countLine)) if (!countLine.empty()) lineCount++;
    fs.clear();
    fs.seekg(0);
    controller.print(0, 0, "MCL %d lines      ", lineCount);
    pros::delay(300);
    if (lineCount == 0) {
        controller.print(0, 0, "FAIL: empty file  ");
        pros::delay(1000);
        return;
    }

    // Start pose = first frame of the route. The route is field-absolute
    // (drawn in the planner / set at record time), so it's self-describing.
    // The passed start_* are fallbacks if the first line won't parse.
    double s_x = start_x_in, s_y = start_y_in, s_t = start_theta_deg;
    {
        std::string firstLine;
        while (std::getline(fs, firstLine)) if (!firstLine.empty()) break;
        Frame f0;
        if (parse_frame(firstLine, f0)) { s_x = f0.x; s_y = f0.y; s_t = f0.t; }
        fs.clear();
        fs.seekg(0);
    }

    // Seed LemLib at field-absolute start, then seed MCL around it.
    const double start_theta_rad = s_t * PI / 180.0;
    chassis.setPose(s_x, s_y, s_t);

    Filter filter;
    init(filter, s_x, s_y, start_theta_rad,
         /*sigma_xy=*/2.0, /*sigma_theta=*/5.0 * PI / 180.0);

    // For body-frame motion model we need odom-pod deltas, not pose deltas.
    // Simpler approximation for the mock: use LemLib pose deltas and treat
    // them as body deltas (rotated by current heading). When you go production,
    // wire vertical_rotation + horizontal_rotation directly.
    lemlib::Pose prevPose = chassis.getPose();

    std::string line;
    int step             = 0;
    int lastWaypointStep = 0;
    double lastHeading   = start_theta_deg;

    bool prev_l1        = false;
    bool prev_right     = false;
    bool prev_x         = true;  // suppress record-start X phantom
    bool wingState      = false;
    bool matchloadState = false;
    bool limiterState   = true;

    while (std::getline(fs, line)) {
        if (line.empty()) continue;

        Frame fr;
        if (!parse_frame(line, fr)) { step++; continue; }

        if (step == 0) {
            controller.print(0, 0, "OK %.1f %.1f %.1f", fr.x, fr.y, fr.t);
            pros::delay(80);
        }

        // Mech replay.
        replay_mech(fr, prev_l1, prev_right, prev_x,
                    wingState, matchloadState, limiterState);

        // ── MCL predict ─────────────────────────────────────────
        lemlib::Pose currPose = chassis.getPose();
        // Convert world-frame pose delta to body-frame for motion model.
        const double dx_w     = currPose.x - prevPose.x;
        const double dy_w     = currPose.y - prevPose.y;
        double dtheta_deg = currPose.theta - prevPose.theta;
        while (dtheta_deg >  180.0) dtheta_deg -= 360.0;
        while (dtheta_deg < -180.0) dtheta_deg += 360.0;
        const double dtheta_w = dtheta_deg * PI / 180.0;
        prevPose = currPose;

        const double th = currPose.theta * PI / 180.0;
        const double sin_th = std::sin(th);
        const double cos_th = std::cos(th);
        // Inverse rotation: world -> body. Body forward is along
        // (sin θ, cos θ) world; body lateral is (cos θ, -sin θ) world.
        const double d_forward = dx_w * sin_th + dy_w * cos_th;
        const double d_lateral = dx_w * cos_th - dy_w * sin_th;

        predict(filter, d_forward, d_lateral, dtheta_w, DEFAULT_ALPHAS);

        // Pin particle orientation to the heading (IMU-backed odom) before
        // the wall updates, so ray/wall association uses the trusted heading
        // instead of drifting particle headings.
        set_heading(filter, th, 1.0 * PI / 180.0);

        // ── MCL update (4 sensors) ──────────────────────────────
        // Read each sensor once; update() gates each reading internally.
        const int f_mm = fdist_sens.get(), f_cf = fdist_sens.get_confidence();
        const int b_mm = bdist_sens.get(), b_cf = bdist_sens.get_confidence();
        const int l_mm = ldist_sens.get(), l_cf = ldist_sens.get_confidence();
        const int r_mm = rdist_sens.get(), r_cf = rdist_sens.get_confidence();
        update(filter, field::FRONT, f_mm, f_cf, R_SENSOR);
        update(filter, field::BACK,  b_mm, b_cf, R_SENSOR);
        update(filter, field::LEFT,  l_mm, l_cf, R_SENSOR);
        update(filter, field::RIGHT, r_mm, r_cf, R_SENSOR);

        summarize(filter);

        // Resample only if effective sample size has crashed.
        if (filter.n_eff < NEFF_RESAMPLE_THRESH) {
            resample(filter);
            summarize(filter);
        }

        // Waypoint planner — every Nth tick.
        if (step % WAYPOINT_SKIP != 0) { step++; continue; }

        // ── Partial-correction target offset ────────────────────
        // drift = MCL belief - LemLib reported pose
        // trust = clamp(1 - var/VAR_FULL_TRUST, 0, 1)
        // target_corrected = waypoint - drift * trust
        const double drift_x = filter.x_mean - currPose.x;
        const double drift_y = filter.y_mean - currPose.y;
        double trust = 1.0 - (filter.var_xy / VAR_FULL_TRUST);
        if (trust < 0.0) trust = 0.0;
        if (trust > 1.0) trust = 1.0;

        const double corrected_target_x = fr.x - drift_x * trust;
        const double corrected_target_y = fr.y - drift_y * trust;

        // ── Standard waypoint planning (same as oekf path) ──────
        const double actX     = currPose.x;
        const double actY     = currPose.y;
        const double actTheta = currPose.theta;

        const double fx   = corrected_target_x - actX;
        const double fy   = corrected_target_y - actY;
        const double dist = std::sqrt(fx*fx + fy*fy);

        const double thetaRad = actTheta * PI / 180.0;
        const double dot      = fx * std::sin(thetaRad) + fy * std::cos(thetaRad);
        const bool goingBackwards = (dist > 1.0) && (dot < 0);

        double headingErr = fr.t - actTheta;
        while (headingErr >  180) headingErr -= 360;
        while (headingErr < -180) headingErr += 360;

        const int framesDelta    = step - lastWaypointStep;
        const int recordedTimeMs = framesDelta * 20;
        const int dynamicTimeout = std::max(200, (int)(recordedTimeMs * TIMEOUT_MULTIPLIER));
        const double recordedSpeedIPS = (recordedTimeMs > 0)
                                        ? (dist / (recordedTimeMs / 1000.0))
                                        : 20.0;
        int dynamicMaxSpeed = (int)(recordedSpeedIPS / MAX_SPEED_IPS * 127.0);
        dynamicMaxSpeed = std::max(MIN_SPEED, std::min(MAX_SPEED, dynamicMaxSpeed));
        float earlyExit = std::min(EARLY_EXIT_MAX,
                                   (float)(dist * 0.4 * (recordedSpeedIPS / MAX_SPEED_IPS)));
        earlyExit = std::max(0.5f, earlyExit);
        lastWaypointStep = step;

        const double turnRatio = (dist > 0.5) ? (std::abs(headingErr) / dist) : 999.0;
        const bool isPureTurn  = (std::abs(headingErr) > TURN_DETECT_DEG) &&
                                 (turnRatio > TURN_RATIO_THRESH || dist < SHORT_MOVE_IN);

        if (isPureTurn) {
            // Pure-turn lookahead: same scan-ahead as oekf path.
            double finalTurnHeading = fr.t;
            std::streampos savedPos = fs.tellg();
            std::string peekLine;
            while (std::getline(fs, peekLine)) {
                if (peekLine.empty()) continue;
                Frame pf;
                if (!parse_frame(peekLine, pf)) continue;
                const double pdx   = pf.x - actX;
                const double pdy   = pf.y - actY;
                const double pdist = std::sqrt(pdx*pdx + pdy*pdy);
                double pherr = pf.t - actTheta;
                while (pherr >  180) pherr -= 360;
                while (pherr < -180) pherr += 360;
                const double pratio = (pdist > 0.5) ? (std::abs(pherr) / pdist) : 999.0;
                const bool stillTurning = (std::abs(pherr) > TURN_DETECT_DEG) &&
                                          (pratio > TURN_RATIO_THRESH || pdist < SHORT_MOVE_IN);
                if (stillTurning) finalTurnHeading = pf.t;
                else break;
            }
            fs.clear();
            fs.seekg(savedPos);

            int turnTimeout = std::max(600, dynamicTimeout);
            chassis.turnToHeading(finalTurnHeading, turnTimeout, {.maxSpeed = 90}, false);

        } else if (dist < SHORT_MOVE_IN) {
            chassis.moveToPoint(corrected_target_x, corrected_target_y, dynamicTimeout,
                                {.forwards = !goingBackwards,
                                 .maxSpeed = (float)std::min(80, dynamicMaxSpeed),
                                 .minSpeed = 0},
                                false);
        } else {
            chassis.moveToPoint(corrected_target_x, corrected_target_y, dynamicTimeout,
                                {.forwards       = !goingBackwards,
                                 .maxSpeed       = (float)dynamicMaxSpeed,
                                 .minSpeed       = (float)MIN_SPEED,
                                 .earlyExitRange = earlyExit},
                                true);
        }

        lastHeading = fr.t;
        step++;
    }

    chassis.waitUntilDone();
    double finalErr = lastHeading - chassis.getPose().theta;
    while (finalErr >  180) finalErr -= 360;
    while (finalErr < -180) finalErr += 360;
    if (std::abs(finalErr) > TURN_THRESHOLD_DEG)
        chassis.turnToHeading(lastHeading, TURN_TIMEOUT_MS, {}, false);

    controller.print(0, 0, "MCL done step %d ", step);
#if !USE_EMBEDDED_ROUTE
    fs.close();
#endif
}

} // namespace mcl


// Flat entry. Uses distance sensors to auto-detect start pose (assumes
// robot is placed facing +Y, theta=0). Override by calling
// mcl::rerun() directly with your own start pose.
void mcl_rerun() {
    lemlib::Pose p = determine_start_pose(0.0);
    mcl::rerun(p.x, p.y, p.theta);
}
